### ISSUE TITLE
Multiple images within a tweet are not picked up

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/weeknote-generator#11]
Specifically this tweet:

https://twitter.com/mcknut/status/576422500130811904

On this weeknotes:

http://doesliverpool.com/weeknotes/week-197-strange-new-machines-and-floating-robots/

**Comment by amcewen** [comment]
Yes, it's been doing that for a while... basically because Twitter lets you now include multiple images but only includes the first one in the text for the tweet :-/

**Comment by amcewen** [comment]
Still seems to be an issue with some tweets, e.g. https://twitter.com/amcewen/status/591903669764886528/photo/1 in http://doesliverpool.com/weeknotes/week-203-showing-off-in-newcastle-at-makerfaire-uk/

**Comment by amcewen** [comment]
Not sure if this can be easily fixed, or fixed at all.  Doing some debugging of this the search results from Twitter don't seem to include the multiple images any more :-/

Maybe we'd need to do extra requests for any tweets with any media set, to get all the info for them?  (Haven't checked if that's possible though)

**Comment by brett-lempereur** [comment]
As I tagged my pull request with the wrong issue, posting here too.  Turns out you should call Twitter::REST::Client#status to retrieve a Twitter::Tweet object with all media attached.  Demonstration at https://gist.github.com/brett-lempereur/7dc68961bc2a20de7be9.

**Comment by brett-lempereur** [comment]
My branch should probably be improved by doing the date/inclusion/retweet check first, putting all of the valid Tweets into an Array, and using the bulk-lookup on batches of 100 tweets (I think sferik/twitter takes care of batching for us) to avoid hammering the Twitter API and falling foul of the rate limit.
