### ISSUE TITLE
Images using http:// URLs

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/weeknote-generator#23]
At least some images are using `http://`, would be better to use `https://` URLs where possible. I looked at the code and did notice a hardcoded `http://` but I wasn't sure just changing that would be appropriate and I was a bit overwhelmed by the config file!

**Comment by amcewen** [comment]
According to @johnmckerrell there were http URLs in some of the Twitter images, which will have come from Twitter like that if so (as that's where the code gets them from).  However, there weren't any images included in this week's weeknotes for me to easily test it.  Reopening this until we've had some test data...

**Comment by amcewen** [comment]
Now we had some test data it was a reasonably easy fix - there's a "media_url_https" attribute as well as the "media_url", so I switched to using that one.
