### ISSUE TITLE
Highlight open issues on GitHub

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/weeknote-generator#25]
Either pick the oldest issue, or a random open issue. Could even be the "Issue of the week" inviting people to swarm on it. Or multiple issues, or the script picks multiple issues but "the editor" (hello @amcewen ) can triage.

**Comment by amcewen** [comment]
I've added code to choose 5 random issues which are (a) open, (b) not new, and (c) are labelled with any of a set of labels given in the config yaml file.

I figured we should be most interested in things that are high priority, so for now it's choosing things that are labelled as "1 - Must DoES" and also "DoES Move".  Whoever is "editing" that week should then pick one out of the five chosen and delete the rest.
