### ISSUE TITLE
Firefox sometimes blocks hot-linked Twitter images

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/weeknote-generator#30]
If you open a private window in Firefox (just in case you're logged into Twitter, which doesn't seem to always show the problem) then it will block the images when you view the weeknotes:

![image](https://user-images.githubusercontent.com/108468/101381629-e1e0c080-38ae-11eb-9f43-e9a885af29d7.png)

If you open the web console you'll see:

![image](https://user-images.githubusercontent.com/108468/101382526-f96c7900-38af-11eb-803a-e54b14c9069c.png)

Looks like it depends on the user's tracking protection setting (that's set to strict on private windows, which is why that triggers it, but other users might have that set similarly in non-private windows) - https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection

**Comment by JackiePease** [comment]
Spoke to @amcewen - this also affects Chrome, depending on tracking protection. Solution would be to download photos to a DoES Liverpool repository

**Comment by amcewen** [comment]
This is complicated the implementation *but* it would be nice if the first time we were saving an image from someone the system could ask for permission for us to use the images.  Something like: `Yes / Just for #weeknotes / No` and then store that decision and use it in the future.

Probably means we'd need a separate script running periodically *during* the week, so there's chance for them to reply before the weeknotes are being compiled (and/or we could carry over late permission-granted messages to the weeknotes immediately after the decision)

**Comment by amcewen** [comment]
We followed the "ask for consent" approach with the Mastodon support.  Given Twitter is dying off and we're not going to pay for API access I'm going to close this as `wontfix`
