### ISSUE TITLE
Images in WeekNotes have a blank coloured bar underneath them.

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/weeknote-generator#37]
There's a blank coloured bar underneath all the Mastodon images that the new Weeknote-generator has pulled in. Presumably needs a different option for Wordpress.
![Screenshot_2024-08-21-13-51-31-36_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/d52f98a2-db25-4955-a39b-11f348ad7416)

**Comment by amcewen** [comment]
Wordpress for some reason turns the `<div><img></div>` into `<figure><img></figure><div></div>`.

I've tweaked the HTML generator to wrap the images in <figure> rather than <div>, so hopefully they'll convert better.
